modLoader = "javafml"
loaderVersion = "[4,)"
license = "Polyform-Shield-1.0.0"

[[mods]]
modId = "sodium"

version = "${version}"
displayName = "Sodium"

iconFile = "sodium-icon.png" #optional

authors = "JellySquid (jellysquid3), IMS212"

credits = "bytzo, PepperCode1, FlashyReese, altrisi, Grayray75, Madis0, Johni0702, comp500, coderbot16, Moulberry, MCRcortex, Altirix, embeddedt, pajicadvance, Kroppeb, douira, burgerindividual, TwistedZero, Leo40Git, haykam821, muzikbike"

description = '''
Sodium is a powerful rendering engine for Minecraft which improves frame rates and reduces lag spikes.
'''

[modproperties.sodium]
"fabric-renderer-api-v1:contains_renderer" = true
"fabric:provides" = ["indium"]

[[mixins]]
config = "sodium-common.mixins.json"

[[mixins]]
config = "sodium-neoforge.mixins.json"

[[mixins]]
config = "sodium-frapi.mixins.json"
requiredMods = ["fabric_renderer_api_v1"]

[[dependencies.sodium]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2.10-beta,)"
ordering = "NONE"
side = "BOTH"
