package net.caffeinemc.mods.sodium.client.render.chunk.lists;

import it.unimi.dsi.fastutil.ints.IntArrays;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.caffeinemc.mods.sodium.client.render.chunk.region.RenderRegion;
import net.caffeinemc.mods.sodium.client.render.viewport.Viewport;

public interface RenderListProvider extends SortItemsProvider {
    ObjectArrayList<ChunkRenderList> getUnsortedRenderLists();

    default SortedRenderLists createRenderLists(Viewport viewport) {
        var sectionPos = viewport.getChunkCoord();
        var unsorted = this.getUnsortedRenderLists();

        // sort the regions by distance to fix rare region ordering problems.
        // regions need to be sorted even when the order is generated by a correctly traversed section tree
        // but sections don't need to be sorted within regions
        var cameraX = sectionPos.getX() >> RenderRegion.REGION_WIDTH_SH;
        var cameraY = sectionPos.getY() >> RenderRegion.REGION_HEIGHT_SH;
        var cameraZ = sectionPos.getZ() >> RenderRegion.REGION_LENGTH_SH;

        var size = unsorted.size();
        var sortItems = this.ensureSortItemsOfLength(size);

        for (var i = 0; i < size; i++) {
            var region = unsorted.get(i).getRegion();
            var x = Math.abs(region.getX() - cameraX);
            var y = Math.abs(region.getY() - cameraY);
            var z = Math.abs(region.getZ() - cameraZ);
            sortItems[i] = (x + y + z) << 16 | i;
        }

        IntArrays.unstableSort(sortItems, 0, size);

        var sorted = new ObjectArrayList<ChunkRenderList>(size);
        for (var i = 0; i < size; i++) {
            var key = sortItems[i];
            var renderList = unsorted.get(key & 0xFFFF);
            sorted.add(renderList);
        }

        for (var list : sorted) {
            list.prepareForRender(sectionPos, this);
        }

        return new SortedRenderLists(sorted);
    }
}
